name: Publish github package

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
    
env:
  REGISTRY: https://npm.pkg.github.com/
  PACKAGE_DIR: Assets/Plugins/Unity.Bindings
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm ci
      - run: npm test
      
  publish-package:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - name: Publish to NPM
      - run: cd ${{ env.PACKAGE_DIR }}
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
