name: Publish github package

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
    
env:
  REGISTRY: https://npm.pkg.github.com/liuwenjiexx/
  PACKAGE_DIR: Assets/Plugins/Unity.Bindings
  
jobs:
  publish-package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    defaults:
      run:
        working-directory: ${{ env.PACKAGE_DIR }}
    steps:      
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: ${{ env.REGISTRY }}
      - name: package dir '${{ env.PACKAGE_DIR }}' 
        run: pwd
 #     - run: npm set registry ${{ env.REGISTRY }}
      - run: npm publish --registry=${{ env.REGISTRY }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
 
