name: Publish github package

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
    
env:
  REGISTRY: https://npm.pkg.github.com/
  PACKAGE_DIR: Assets/Plugins/Unity.Bindings
  
jobs:
  publish-package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: ${{ env.REGISTRY }}
      - name: package dir '${{ env.PACKAGE_DIR }}' 
      - working-directory: ${{ env.PACKAGE_DIR }}
      - run: pwd
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
